### ISSUE TITLE
[Feature requests] modbus rs485 und merfachnetz support

### ISSUE THREAD

**Issue by Mikroprozessori** [reserve85/HoymilesZeroExport#106]
Ich habe mich gefragt ob es möglich wäre mehrere Stromzähler einzubinden und Wechselrichter zuzuordnen. ein befreundeter Vermieter möchte aus einer zentralen Batterie die einzelnen Wohnungen versorgen. Meine Idee war das alle Wechselrichter im Batterie raum sind und 230V leitungen und daten leitungen zu den wohnungsschaltschränken führen.

**Comment by reserve85** [comment]
Hi,

nein ist nicht möglich - aber du kannst das Script mit mehreren Instanzen starten.
