### ISSUE TITLE
Autostart  

### ISSUE THREAD

**Issue by tthnn** [reserve85/HoymilesZeroExport#113]
Hi . ich wusste keine andere Kontaktmöglichkeit 

Kann es sein das nach der installation in linux der Skript jedes mal Automatisch beim einschalten des pcs  startet ?
Bzw kann diese funktion hinzugefügt werden ?

Viele Grüße

**Comment by reserve85** [comment]
Hi, 

Ja, in Linux läuft das als Service automatisch.
unter Windows geht das so: https://stackoverflow.com/a/66016922

Gruß
