### ISSUE TITLE
PowerLimit Änderung mit Ahoy Versionen >= 0.8.39

### ISSUE THREAD

**Issue by Ollipop030** [reserve85/HoymilesZeroExport#116]
Moin moin,

bei der neuen Ahoy Version gab es eine Änderung:

`BREAKING CHANGE: powerlimit (active power control) now has one decimal place (MqTT / API) #1199`

Das muss im Script noch berücksichtigt werden, ansonsten wird das Limit nur auf max. 10% gesetzt.

**Comment by reserve85** [comment]
ich bin leider unterwegs, aber so ganz kapiere ich es nicht: 
muss ich dann nun "400,0" für 400W senden oder "400.0" oder "4000"?
Wieso geht einfach "400" für 400W nicht mehr? Das finde ich nicht so elegant gelöst...

**Comment by Ollipop030** [comment]
Ja, ist auch nicht logisch. Aber lieber noch mal abwarten, gibt grad ein Issue bei Ahoy dazu. 
https://github.com/lumapu/ahoy/issues/1313

Im Moment ist es tatsächlich so, sobald das Script 1500 Watt an Ahoy sendet, wird das Limit auf 150W gesetzt.

**Comment by Ollipop030** [comment]
Jo bestens! Ich installiere das mal, aber hier ist halt null Sonne seit Wochen.
Vielen Dank.

**Comment by Ollipop030** [comment]
Habe das Issue bei Ahoy weiter verfolgt, dort sind jetzt sehr gute Infos für das Senden des Limits gepostet worden. Anscheinend sind die Hoymiles empfindlich, was das wiederholte Limit setzen mit gleichem Wert betrifft. Dazu mal eine Frage:

In der Ini gibt es ja diesen Punkt:

```
# defines how often a identical limit will be set, set it to "-1" for disabled (infinite repeat)
SET_LIMIT_RETRY = 2
```

Wie kann ich das komplett deaktivieren? Auf 0? Auf -1 sendet es ja unendlich lange. Vielleicht sollte man die Funktion auch komplett entfernen, wobei ich damit aber auch noch nie Probleme hatte.

**Comment by reserve85** [comment]
Muss ich morgen mal schauen, glaub das hab ich mit 0 nie probiert… jedenfalls hab ich schon immer 10 Wiederholung eingestellt und hatte damit noch NIE ein Problem…

**Comment by reserve85** [comment]
Gerade nochmal geschaut: SET_LIMIT_RETRY = 2 bedeutet, dass das Limit maximal 2 mal gesetzt wird.
Wenn du es also nicht wiederholen willst musst du eine 1 eintragen (1 mal setzen).
Übrigens wird das "Wiederholen" nur im Fehlerfall durchgeführt (wenn das ACK nicht bestätigt wurde).
