### ISSUE TITLE
Fehler bei der Installation auf Raspberry Pi 2 zero w - Docker

### ISSUE THREAD

**Issue by crisi-solar** [reserve85/HoymilesZeroExport#122]
Hallo, habe heute komplett alles neu auf eine 64 GB-MicroSD-Karte installiert, erhalte aber beim installieren im Dockerteil diese Fehlermeldungen:

![Screenshot 2024-01-13 195937](https://github.com/reserve85/HoymilesZeroExport/assets/156539713/323bbc42-c268-4ea8-be28-be5aa2c847a2)

**Comment by reserve85** [comment]
Da kann ich leider wenig helfen, da ich kein Docker in Verwendung habe. 
Ggf. könnte hier @irrwitzer42 oder @tomquist unterstützen?

**Comment by irrwitzer42** [comment]
Hi @crisi-solar ,
zu allererst: ich habe das HoymilesZeroExport auf nem Pi 4 in Docker laufen, nicht auf einem Pi Zero - das _kann_ einen Unterschied machen.

Der untere Teil Deines Screenshots ist einfach zu lösen: Das "Skript" in der Readme unter Docker/docker-compose musst Du kopieren und innerhalb des Ordners, in dem Du das Python-skript und die Configs liegen hast, in eine neue Datei namens "docker-compose.yml" einfügen (z.B. mit nano, pico, vi, emacs...)
Anschliessend kannst Du disen docker "stack" dann mit
`docker-compose up -d`  bzw. `docker compose up -d` starten (startet dann bei Reboot auch automatisch wieder mit).

Falls docker-compose bei Dir noch nicht installiert ist:
`apt install docker.io docker-compose`

Im manuellen docker run  im oberen Teil Deines Screenshots ist glaube ich noch ein Fehler drin. Probiers mal mit:

`docker run -d --name hoymileszeroexport \
    -v ${PWD}/HoymilesZeroExport_Config_Override.ini:/app/HoymilesZeroExport_Config_Override.ini \
    ghcr.io/reserve85/hoymileszeroexport:main -c /app/HoymilesZeroExport_Config_Override.ini`

Man beachte hier den anderen Pfad für den Parameter -c beim Aufruf. Das könnte das "no such file or directory" erklären, aber wieso da "unknown" steht, weiss ich nicht.

Good luck! Und gib bitte kurz Bescheid, obs dann funktioniert.

**Comment by reserve85** [comment]
das `-c /app/HoymilesZeroExport_Config_Override.ini` müsste dann noch in der readme angepasst werden wenn es funktioniert.?!

**Comment by irrwitzer42** [comment]
Ja genau, falls Crisi-Solar positives Feedback gibt, kriegts Du noch nen PR mit ein paar readme Anpassungen, vielleicht etwas mehr Howto.

**Comment by karrenbauer** [comment]
gibt es eine einfache Anleitung, wie man das Ganze in eine Synology DS918 mit Docker machen kann?

**Comment by irrwitzer42** [comment]
@karrenbauer ich würde annehmen, dass das mit den Infos (docker parameter / docker-compose file) aus der readme genauso funktionieren würde, wie mit jedem anderen Docker Container auf der Synology. Mangels eigenem NAS kann ich das jedoch nicht ausprobieren.

**Comment by tomquist** [comment]
@crisi-solar Ich habe einen fix hier: https://github.com/reserve85/HoymilesZeroExport/pull/123

Das Problem was, dass das Alpine image die Python binary nicht finden kann weil es das build result vom inkompatiblem Debian nutzt.

**Comment by crisi-solar** [comment]
Hallo!
Sorry dass ich mich erst jetzt melde, habe inzwischen eine Lösung mit der Nulleinspeisung direkt auf der openDTU onBattery laufen, funktioniert super und es wird keine zweite Hardware benötigt.
Trotzdem vielen Dank und sorry dass ich euch mit meinem Problem hier belästigt habe.
