### ISSUE TITLE
Powerlimit wegen Akku betrieb auf x setzen

### ISSUE THREAD

**Issue by tbretz65** [reserve85/HoymilesZeroExport#127]
Hallo,
ist es möglich das Powerlimit z.B. auf xxxWatt zwischen Sonnenuntergang und Sonnenaufgang zu setzen.
Somit könnte man die Entladung des Akkus (B2500) begrenzen.
Oder kann man das anders regulieren ?

Danke

**Comment by reserve85** [comment]
Hi, das geht so "out of the box" nicht.

Aber es gibt einen Workaround. 
Du bräuchtest zwei configs: eine für Tagsüber und eine für Nachts (z.b. config_day_override.ini und config_night_override.ini). 

Dann müsstest du mit einem cron-job jeweils zum sonnenaufgang / sonnenuntergang die HoymilesZeroExport_Config_Override.ini überschreiben und das Script neu starten. 

Zeitlich klappt das z.B. so: https://raspberrypi.stackexchange.com/questions/90099/execute-a-script-at-sunrise-sunset

**Comment by tbretz65** [comment]
Ok.
Danke für die Info.
Hab ich mit cron und zusätzlicher config am laufen.
:-)
