### ISSUE TITLE
Ständige Limiterhöhung, langsame Limitreduzierung

### ISSUE THREAD

**Issue by Ollipop030** [reserve85/HoymilesZeroExport#13]
Mir ist noch folgendes aufgefallen:

Das Limit wird ja, wenn nicht genug produziert wird, immer weiter erhöht. Vor ein paar Tagen habe ich das schonmal bemerkt, jetzt konnte ich es dokumentieren:

Wenn sich eine Wolke vor die Sonne schiebt, ich dann aber nur -10 Watt einspeise, wird da das Limit erhöht. Und erhöht, und erhöht. Bis ich beim Maximum von 1800W WR Leistung bin. Durch die Wolke speise ich aber immer noch -10 Watt ein. Wenn jetzt die Sonne wieder rauskommt speise ich mit voller Leistung ein, das Limit wird dann langsam wieder runtergeschraubt, das Script weiß ja aber nicht wieviel Leistung ich tatsächlich brauche (in diesem Beispiel 300 Watt). Um aber von 1800W auf 300W runterzuregeln dauert es mehre Minuten. Im angehängten Logfile bemerkt das Script eine Überproduktion um 13:47:38, bis ich wieder beim gewünschten Einspeisewert bin dauert es bis 2023-03-20 13:51:11. Das sind satte 3,5 Minuten bis ich wieder die geschünschte Leistung einspeise.

Kann man die Leistungsreduzierung irgendwie beschleunigen? Meinetwegen um einen festulegenden Prozentwert von HOY_MAX_WATT? Denn wenn ich direkt um 500 Watt reduzieren kann, dauert es dann (bei mir mit 13 Sekunden Intervall) 26 Sekunden um 1000 Watt zu reduzieren, dann nochmal 13 Sekunden bis es wieder passt.

3,5 Minuten sind echt lang, und ich habe nur 1800Watt maximale Leistung. Bei noch größeren Anlagen (und 20 Sekunden Intervall) dauert es ja noch viel länger.
[Log 200323.txt](https://github.com/reserve85/HoymilesZeroExport/files/11018734/Log.200323.txt)

**Comment by reserve85** [comment]
Yep, konnte ich auch schon ein paar mal nachvollziehen und habe ich auf der "ToDo"... 

Es wird immer um die Differenz vom Sollwert zum Istwert die Leistung angepasst und das ist bei dem Beispiel eben nicht so viel. Ich würde das denke ich nur hinbekommen, wenn direkt über die API von Ahoy der reale IST-Wert ausgelesen wird - das hatte jedoch nicht so gut funktioniert und führte zu mehr Problemen. Im AHOY hatten die Werte teilweise ziemlich lange hinterhergehinkt. So war nämlich meine erste ursprüngliche Implementierung aufgebaut und ich habe es dann um die "Differenzanpassung" abgeändert.

Vielleicht fällt mir noch was ein.

**Comment by Ollipop030** [comment]
Jetzt wird es interessant: Den realen Wert der PV Leistung kann ich von meinem ORNO Zwischenzähler bekommen, den kann ich sogar per json abfragen. Wird dir das zu auswändig? Ich weiß nicht, ob das noch jmd anderes dann auch so brauchen könnte.

**Comment by reserve85** [comment]
Ah, das würde ja dann auch über die 2.7.0 gehen?

**Comment by reserve85** [comment]
Ja nach ein bisschen überlegen bringt mir das mit dem 2.7.0 Wert quasi nix. 
Probiere mal die DEV - ich frage das jetzt doch nochmal vom AHOY ab. 
Ich versuche da das Limit einzuschränken, in Abhängigkeit vom echten Power-Output. Sprich: das Limit wird ab eiunem gewissen Grenzwert abgeschnitten falls der Output nicht hinterherkommt. In der Config kannst du den Grenzwert angeben, z.B. 10% von MaxPower. (Wenn Limit > 10% über IstOutput -> schneide ab). 

Funktionierte hier jetzt erstmal ganz gut...

**Comment by Ollipop030** [comment]
Guten Morgen,

hab die Änderungen mal übernommen, hier ist schon wieder Mistwetter, mal sehen ob ich das effektiv heute testen kann.

Aber nochmal zur Berechnung des echten Verbrauchs: Du kannst ja genau bestimmen, wie das Limit zu setzen ist, wenn plötzlich die Sonne rauskommt. Über die Rest API von Ahoy kann man total power AC ziehen, das ist ja der Wert der tatsächlich produziert wird. Das Script hat ja das Limit wie bei mir bei der Wolke bis auf 1800 Watt gesetzt, weil es immer versucht mehr Leistung rauszuholen. Wenn jetzt die Sonne wiederkommt, die Leistung rapide ansteigt bekommt Ahoy das ja mit. 

Vielleicht sollte das Script ab und zu mal bei Ahoy horchen, ob Hoy_Max_Watt mit der tatsächlichen Leistung übereinstimmt. Genau wie jetzt gerade auch: Hier ist ziemlich bewölkt, Limit ist jetzt auf 1800 Watt. Ahoy sagt aber, ich produziere 106 Watt. Also KÖNNTE ja per Script auch auf 120 Watt geregelt werden. Der Stromzähler sagt aber, ich ziehe gerade 130 Watt aus dem Netz. Das Script setzt jetzt das Limit auf 120 Watt + 130 Watt, also 250 Watt. Wenn dann aber total power AC NICHT gestiegen ist, dann wieder runter auf den Ursprungswert (120Watt). Beim nächsten Durchlauf wieder von vorn. So wird schonmal verhindert, dass das Script die Leistung bis auf Maximum dreht.
Wenn jetzt die Sonne plötzlich rauskommt dauert es ja nur einen Durchlauf, bis die Leistung wieder passt. Beispiel:

total power AC ist bei 150 Watt, Sonne kommt gerade raus und scheint mit voller Kraft. Laut Stromzähler fehlen aber 250 Watt, Also neues Limit auf 400 Watt (plus den Toleranzwert aus der *.ini evtl). 
Wenn die Sonne wieder verschwindet, beginnt das Script von vorn: Limit wird von 400W wieder gesenkt auf total power AC vom Ahoy, da die Differenz zwischen gesetztem Limit und tatsächlicher Leistung zu groß ist. 

Verstehts du wie ich das meine?

**Comment by reserve85** [comment]
klingt alles logisch, ist aber nicht einfach. Ahoy hat unter gewissen umständen eine ewig lange Verzögerung: z.B. du setzt das Limit, dann dauert es schonmal bis zu 5s bis das aktiv ist falls es wiederholt gesendet wird. Dann dauerts wieder bis zu 7s bis die Werte aktualisiert vom Inverter zurückkommen. Und falls da noch bei der Übertragung was schief geht noch länger...

Außerdem: wenn bei mir ein oder zwei Module verschattet sind, dann haut die Berechnung des Limits nicht hin. Die Inverter rechnen da intern irgendwie anders. Das kann dann sogar sein, dass du 150W als Limit eingestellt hast aber 220 rauskommen. Deswegen gehe ich über den Zähler und passe es differenzmäßig an.

**Comment by reserve85** [comment]
ah genau, die Richtung war es. Keine Über- sondern Unterproduktion.

**Comment by reserve85** [comment]
Jupp, die Erfahrung hatte ich auch gemacht.
Heute hatte ich damit allerdings keine Probleme, kann natürlich auch sein dass ich nur einen Inverter habe.
Ich würde daher die Änderung mal drin lassen und defaultmäßig deaktivieren?

**Comment by Ollipop030** [comment]
Vielleicht werden die kommenden Ahoy Versionen da ja noch schneller, selbst bei 2 Invertern sollte ein Durchlauf nicht sooo lange dauern. Beim HM 300 war die letzte Kommunikation vorhin einmal sogar 7 Minuten her.

Reicht ja, wenn ich  MAX_DIFFERENCE_BETWEEN_LIMIT_AND_OUTPUTPOWER auf 100 setze?

**Comment by reserve85** [comment]
Sollte im Prinzip recht einfach sein, aber passt irgendwie nicht in den Code?

**Comment by Ollipop030** [comment]
Hahaha, nein, der Zähler selbst steckt schon in der Unterverteilung. Ich meinte eine Abfrage des Zählers über das Script. Habe mir gestern noch ein paar andere Projekte bzgl. der Nulleinspeisung angesehen. Die meisten arbeiten mit dem tatsächlich erzeugten Wert. Nun dauert es bekanntlich bei Ahoy manchmal sehr lange, bis aktuelle Daten kommen, hast du Erfahrungen mit OpenDTU? Geht es da schneller? Ich würde mir sonst mal einen zusammenbasteln.

**Comment by reserve85** [comment]
ja, das wird halt gleich kompliziert, wäre besser du machst das separat in deinem Script. Musst nur hier:

```
def CutLimitToProduction(pSetpoint):
    if pSetpoint != GetMaxWattFromAllInverters():
        ActualPower = GetHoymilesActualPower()
...
```

ersetzen durch

```
def CutLimitToProduction(pSetpoint):
    if pSetpoint != GetMaxWattFromAllInverters():
        ActualPower = GetZwischenzaehlerActualPower()
...
```

und die neue Funktion für den Zwischenzähler eintragen, angelehnt an z.b. tasmota:
```
def GetZwischenzaehlerActualPower(pInverterId):
    url = f'http://{TASMOTA_IP}/cm?cmnd=status%2010'
    ParsedData = requests.get(url).json()
    Watts = int(ParsedData[TASMOTA_JSON_STATUS][TASMOTA_JSON_PAYLOAD_MQTT_PREFIX][TASMOTA_JSON_POWER_MQTT_LABEL])
    logging.info("powermeter: %s %s",Watts," Watt")
    return int(Watts)
```

**Comment by Ollipop030** [comment]
Jo besten Dank, die Krücke läuft. Ich hab ein paar Änderungen gemacht:

```
def GetZwischenzaehlerActualPower():
    url = f'http://{TASMOTA_IP}/pages/getinformation.php?heute&meterindex=3'
    ParsedData = requests.get(url).json()
    Watts = int(ParsedData['Leistung170'])
    logging.info("actual producing: %s %s",Watts," Watt")
    return int(Watts)
```

Bei der ersten Zeile stand in den Klammern noch `pInverterId` ist das wichtig? Da kam sonst immer eine Fehlermeldung.

So sieht der Output aus:

> 2023-03-22 09:02:00 INFO     powermeter: -67  Watt
> 2023-03-22 09:02:01 INFO     powermeter: -67  Watt
> 2023-03-22 09:02:02 INFO     powermeter: -67  Watt
> 2023-03-22 09:02:03 INFO     powermeter: -67  Watt
> 2023-03-22 09:02:04 INFO     powermeter: -67  Watt
> 2023-03-22 09:02:05 INFO     powermeter: -67  Watt
> 2023-03-22 09:02:06 INFO     powermeter: -67  Watt
> 2023-03-22 09:02:07 INFO     powermeter: -67  Watt
> 2023-03-22 09:02:08 INFO     powermeter: -67  Watt
> 2023-03-22 09:02:09 INFO     actual producing: 184  Watt
> 2023-03-22 09:02:09 INFO     Inverter 0 reachable: True
> 2023-03-22 09:02:09 INFO     Inverter 1 reachable: True
> 2023-03-22 09:02:09 INFO     powermeter: -67  Watt
> 2023-03-22 09:02:11 INFO     powermeter: -67  Watt
> 2023-03-22 09:02:12 INFO     powermeter: -67  Watt
> 2023-03-22 09:02:13 INFO     powermeter: -67  Watt
> 2023-03-22 09:02:14 INFO     powermeter: -67  Watt
> 

Ich denke, die Änderung wäre grundsätzlich ganz gut, denn viele Leute mit einer PV Anlage haben auch einen Zähler dazwischen. Ich verbaue für sowas immer gern einen Shelly.

**Comment by reserve85** [comment]
ok, ja das war nur copy paste, die InverterID hat sich noch mit reingeschlichen.
Probiere das so mal aus, wie ich das möglichst "dynamisch" implementieren kann muss ich mir mal überlegen. Ist ja dann prinzipiell auch wieder Tasmota, Shelly und SHRDZM möglich...

**Comment by Ollipop030** [comment]
> 2023-03-22 09:12:07 INFO     actual producing: 257  Watt
> 2023-03-22 09:12:07 INFO     Cut limit to 437 Watt, limit was higher than 10 percent of live-production
> 2023-03-22 09:12:07 INFO     Inverter 0 reachable: True
> 2023-03-22 09:12:07 INFO     Inverter 1 reachable: True
> 2023-03-22 09:12:07 INFO     powermeter: 23  Watt
> 2023-03-22 09:12:07 INFO     setting new limit to 535 Watt
> 2023-03-22 09:12:07 INFO     Inverter 0: setting new limit from 447 Watt to 445 Watt
> 2023-03-22 09:12:08 INFO     Inverter 1: setting new limit from 89 Watt to 89 Watt

Sieht gut aus. Noch eine Frage: Er schneidet das Limit bei 437 ab, setzt es aber auf 535. Ist das so richtig oder wird das falsch berechnet?

**Comment by reserve85** [comment]
Ja, das ist verwirrend aber das Abschneiden bezieht sich nur auf das "nächste Basis-Limit" mit dem gerechnet wird. Das wirkt sich somit immer erst auf den nächsten Durchlauf aus.

**Comment by Ollipop030** [comment]
Heidiho,

habe die Änderung jetzt mehrere Tage am Laufen, bin sehr zufrieden damit. Selbst gestern, ständig Wolken/Sonne im Wechsel und nur knapp 0,3KWh eingespeist.
Hast du vor das Cutlimit mit separatem Zähler dauerhaft mit einzubauen?

**Comment by reserve85** [comment]
Ja geh ich an sobald ich dazu komme.

**Comment by reserve85** [comment]
siehe aktuelle dev Version - kannst du es mal probieren?

**Comment by Ollipop030** [comment]
Kannst du bei Tasmota die negativ Berechnung wieder rausnehmen? Das sind ja reine Erzeugungszähler, die haben eigenlich immer einen positiven Wert und gehen nicht ins minus.

**Comment by reserve85** [comment]
Jein, würde es gerne gleich lassen. Wird wahrscheinlich nie gebraucht, aber für den Code ist es Wiederverwendung. Gleiches gilt auch für den SHRDZM...

**Comment by Ollipop030** [comment]
Ok, aber erwartet das Script so nicht einen negativen Wert?

**Comment by reserve85** [comment]
Ich stehe auf dem Schlauch?

**Comment by Ollipop030** [comment]
Bei Tasmota erwartet das Script doch einen negativen Wert, wenn er nicht negativ ist wird er dahin umgerechnet. Das bertrifft aber nur die Stromzähler selbst. Die Zwischenzähler für die PV Produktion sind reine Zähler mit einem positiven Wert, kleiner als 0 geht nicht.

**Comment by reserve85** [comment]
Nee, ich erwarte eigentlich was positives oder wo wird das negativ gerechnet? Kommt immer drauf an wie du den Zähler anschließt. Alternativ kannst du dann in der Config die beiden Labels tauschen.

**Comment by Ollipop030** [comment]
Genau da ist das Problem. Es gibt ja nur eine Label, eben für die Produktion. Und meinem Zähler ist der Einbau auch egal, der Wert ist immer positiv. Aber ich berechne jetzt mal mit einer Variable, die immer 0 ist, dann sollte der Zähler wieder negativ werden.

**Comment by reserve85** [comment]
ich versteh es nicht :-)
Wenn ein normaler Zähler mit OBIS nach der PV-Anlage angeschlossen wird, dann wird der doch so angeschlossen, dass "Grid" 1.7.0 ist? Also ist der CURR_W auch positiv sobald die PV was einspeist? Oder hab ich einen Denkfehler? Soll ich noch eine "Invert"-Option einbauen?

**Comment by Ollipop030** [comment]
Das ist alles richtig. Also darf unter [INTERMEDIATE_TASMOTA] TASMOTA_JSON_POWER_MQTT_LABEL_INTERMEDIATE = curr_w der Wert auch positv sein? Am Lesekopf ist ja immer die Berechnung ins negative notwendig.

Wenn curr_w immer positiv erwartet wird, dann kann doch eigentlich 

# Power-MQTT Input label (positive active instantaneous power, e.g. OBIS Code 1.7.0)
TASMOTA_JSON_POWER_INPUT_MQTT_LABEL_INTERMEDIATE = Leistung270
# Power-MQTT output label (negative active instantaneous power, e.g. OBIS Code 2.7.0)
TASMOTA_JSON_POWER_OUTPUT_MQTT_LABEL_INTERMEDIATE = Leistung170

wieder raus oder?

**Comment by reserve85** [comment]
ahso, ja da hast du recht, den zweiten Fall wird es wohl nie geben. Oder soll ich einfach erstmal nur den Shelly einbauen bis jemand mit einem Tasmota oder so um die Ecke kommt?

**Comment by Ollipop030** [comment]
Ne lass ruhig drin, ich konfiguriere das bei mir immer unter Tasmota. Scheint übrigens zu laufen:

2023-03-27 09:44:40 INFO     setting new limit to 540 Watt
2023-03-27 09:44:40 INFO     Inverter 0: setting new limit from 1500 Watt to 450 Watt
2023-03-27 09:44:41 INFO     Inverter 1: setting new limit from 300 Watt to 90 Watt
2023-03-27 09:44:42 INFO     Inverter 0 reachable: True
2023-03-27 09:44:42 INFO     Inverter 1 reachable: True
2023-03-27 09:44:42 INFO     powermeter: -234  Watt
2023-03-27 09:44:43 INFO     powermeter: -234  Watt
2023-03-27 09:44:44 INFO     powermeter: -234  Watt
2023-03-27 09:44:45 INFO     powermeter: -234  Watt
2023-03-27 09:44:46 INFO     powermeter: -234  Watt
2023-03-27 09:44:47 INFO     powermeter: -234  Watt
2023-03-27 09:44:48 INFO     powermeter: -234  Watt
2023-03-27 09:44:49 INFO     powermeter: -234  Watt
2023-03-27 09:44:50 INFO     powermeter: -234  Watt
2023-03-27 09:44:51 INFO     powermeter: -234  Watt
2023-03-27 09:44:52 INFO     powermeter: 43  Watt
2023-03-27 09:44:52 INFO     setting new limit to 643 Watt
2023-03-27 09:44:52 INFO     Inverter 0: setting new limit from 450 Watt to 535 Watt
2023-03-27 09:44:53 INFO     Inverter 1: setting new limit from 90 Watt to 107 Watt
2023-03-27 09:44:56 INFO     intermediate meter: 385  Watt
2023-03-27 09:44:56 INFO     Cut limit to 565 Watt, limit was higher than 10 percent of live-production
2023-03-27 09:44:56 INFO     Inverter 0 reachable: True
2023-03-27 09:44:57 INFO     Inverter 1 reachable: True
2023-03-27 09:44:57 INFO     powermeter: 43  Watt
2023-03-27 09:44:57 INFO     setting new limit to 668 Watt
2023-03-27 09:44:57 INFO     Inverter 0: setting new limit from 535 Watt to 556 Watt
2023-03-27 09:44:58 INFO     Inverter 1: setting new limit from 107 Watt to 111 Watt
2023-03-27 09:45:11 INFO     intermediate meter: 440  Watt
2023-03-27 09:45:11 INFO     Cut limit to 620 Watt, limit was higher than 10 percent of live-production
2023-03-27 09:45:11 INFO     Inverter 0 reachable: True
2023-03-27 09:45:11 INFO     Inverter 1 reachable: True
2023-03-27 09:45:11 INFO     powermeter: 4  Watt
2023-03-27 09:45:11 INFO     setting new limit to 684 Watt

**Comment by reserve85** [comment]
ok, hab es nochmal geupdated, könntest du das auch nochmal laufen lassen?

**Comment by Ollipop030** [comment]
V1.13 läuft. Genau so hab ich das gemeint. Danke dir.

**Comment by reserve85** [comment]
Kann ich also in die MAIN schieben?

**Comment by Ollipop030** [comment]
Würde sagen ja. Bei mir alles stabil, und es wird wie erwartet angepasst.

**Comment by reserve85** [comment]
gesagt, getan. ich mach hier dann zu?

**Comment by Ollipop030** [comment]
Jepp.
