### ISSUE TITLE
Start HoymilesZeroExport 

### ISSUE THREAD

**Issue by echo1483** [reserve85/HoymilesZeroExport#130]
Noch eine Anfägerfrage. 
Muss man eingentlich HoymilesZeroExport jedesmal manuel starten damit das Programm läuft.
Ich habe das Gefühl HoymilesZeroExport arbeitet nur wenn ich den Befehl sudo python3 HoymilesZeroExport.py ausführe.
Das wäre schon blöd jedesmal HoymilesZeroExport von Hand zu starten. Wenn das so wäre gibt es eine Möglichkeit den Start zu automatisieren. 
LG und Danke Paul

**Comment by irrwitzer42** [comment]
Hi @echo1483,hast Du das Programm bisher nur heruntergeladen, oder es auch gemäß dem Abschnitt “Linux Installation” in der README.md installiert?Das install.sh Skript erstellt eigentlich ein Service-File und aktiviert dieses, sodass das Programm beim Reboot als Daemon gestartet wird.Das kannst Du zB mitsystemctl —list-units | grep Hoymilesüberprüfen.sonst einfach mal das Install Skript ausführen:sudo bash install.shVGOn 27. Jan 2024, at 10:28, echo1483 ***@***.***> wrote:﻿
Noch eine Anfägerfrage.
Muss man eingentlich HoymilesZeroExport jedesmal manuel starten damit das Programm läuft.
Ich habe das Gefühl HoymilesZeroExport arbeitet nur wenn ich den Befehl sudo python3 HoymilesZeroExport.py ausführe.
Das wäre schon blöd jedesmal HoymilesZeroExport von Hand zu starten. Wenn das so wäre gibt es eine Möglichkeit den Start zu automatisieren.
LG und Danke Paul

**Comment by echo1483** [comment]
Danke für die schnelle Antwort. Ich bin genau nach Anleitung vorgegangen und habe den Raspi neu gestartet. Momentan läuft alles wie es soll. Mir ist nur aufgefallen das am nächsten Tag die Steuerung nicht funktioniert, Wenn ich den Befehl sudo python3 HoymilesZeroExport.py ausführe ist alles wieder OK.

**Comment by reserve85** [comment]
Dann stimmt was nicht, das script sollte automatisch starten. 
Hast du vielleicht zum schluss versehentlich sudo ./uninstall_service.sh ausgeführt?

**Comment by echo1483** [comment]
@reserve85
Alles OK, Danke für deine Arbeit hatte wohl einen kleinen Fehler gemacht.
LG Paul
