### ISSUE TITLE
Feature Request: Changelog, Log als Datei ausgeben

### ISSUE THREAD

**Issue by Ollipop030** [reserve85/HoymilesZeroExport#14]
Hi,

ich mach der Übersichtlichkeit halber mal ein neues Issue auf. Wäre es möglich eine Changelog Datei anzulegen? Ich speichere für den Fehlerfall immer die alten Versionen in ein Verzeichnis, weiß aber gar nicht welche Änderungen es da immer gab.

Des Weiteren:
Gibt es eine Möglichkeit eine Logdatei zu schreiben beim Starten des Scripts? Wenn das auf Linux als Dienst läuft geht das ja ohne Weiteres, aber testweise starte ich neue Versionen einfach so über die Kommandozeile, da wird dann nichts geloggt. Reicht ja, wenn einfach ein Textfile erzeugt wird pro Tag.

**Comment by reserve85** [comment]
Changelog kann ich gerne machen. Bei den Logs bin ich überfragt, ich recherchiere mal wenn ich Zeit habe

**Comment by reserve85** [comment]
Logfiles in Datei speichern ist nun implementiert, Changelog ebenso
