### ISSUE TITLE
Nach OpenDTU Update bekomme ich " Exception at GetHoymilesActualPower "

### ISSUE THREAD

**Issue by KEausW** [reserve85/HoymilesZeroExport#141]
Hallo,
und erst mal vielen Dank für Eure coole Arbeit. :-)
Bisher hat das auch richtig super Funktioniert. Ich habe einen HM-1500 und nutze openDTU.
Gestern habe ich die openDTU auf die neuste Version V24.2.16 aktualisiert und seitdem
bekomme ich diesen Error "Exception at GetHoymilesActualPower" und "AC" in der zweiten Zeile.
Habt Ihr einen Tip für mich was ich tun könnte damit es wieder klappt ?

Grüße Karsten

**Comment by reserve85** [comment]
Ja du musst das Script updaten. Die aktuelle Version unterstützt auch die neue OpenDTU Version.

**Comment by KEausW** [comment]
Dankeschön :-) werde ich gleich mal machen.
