### ISSUE TITLE
Hoymiles HMS

### ISSUE THREAD

**Issue by smaicloud** [reserve85/HoymilesZeroExport#146]
Hi,

funktioniert aktuell wirklich nur der HM oder auch der HMS?

**Comment by lullatscho** [comment]
Hab vor zwei Wochen HMS1600 in Betrieb genommen und funktioniert ohne Probleme

**Comment by smaicloud** [comment]
Dann lohnt es sich zu testen. Danke. Werde einen Shelly 1 Pro PM als Zwischenzähler nehmen, der sollte sicher auch laufen. Ich werde berichten.
