### ISSUE TITLE
Zwischenzähler

### ISSUE THREAD

**Issue by smaicloud** [reserve85/HoymilesZeroExport#147]
Das Script läuft prima im Docker Container auf meiner NAS. Ich habe einen Shelly 1 Pro als Zwischenzähler drin. In der Config ist der Shelly auf true und die IP ist auch drin. Allerdings holt er sich die Werte nur von der DTU ab. Ich kann den Traffic in meiner Firewall sehen, er spricht nicht mit dem 1 Pro. Im Container Logfile schaut auch alles gut aus, nur Infos. Habe ich irgendwo vergessen den Zwischenzähler zu aktivieren?

**Comment by reserve85** [comment]
Der wird nur beim regeln irgendwann abgefragt. Wenn du das Script startest wird er auch beim Init ein mal abgefragt.

**Comment by smaicloud** [comment]
![grafik](https://github.com/reserve85/HoymilesZeroExport/assets/39032310/ece1dc3d-5623-4216-9e72-7fd08e6abf36)
So ist es :-)

Kannst ja noch die Hardware in der readme anpassen... HMS läuft und ein Pro 1 EM geht auch...

**Comment by reserve85** [comment]
Übrigens der intermediate meter stimmt noch nicht, da steht noch OpenDTU und kein Shelly: du musst 
USE_SHELLY_1PM_INTERMEDIATE = true
oder
USE_SHELLY_PLUS_1PM_INTERMEDIATE = true
setzen. Ob der Pro geht müsstest du mal probieren, ggf. müsste der noch ergänzt werden.

**Comment by smaicloud** [comment]
Den 1 PM habe ich auf true.  Probiere mal den Plus und checke das morgen nochmal.

**Comment by reserve85** [comment]
USE_SHELLY_PLUS_1PM_INTERMEDIATE = true
das sollte die gleiche API sein wie der 1 PRO, sollte klappen!

**Comment by smaicloud** [comment]
Ja ich muss noch drehen. Aber wenn es bei >1 die DTU machen soll baue ich den wieder raus.

**Comment by reserve85** [comment]
ne muss nicht die DTU machen, wenn alle WR über das Teil gehen passts ja.

**Comment by smaicloud** [comment]
Ich würde dann mal den Sonoff SPM testen. Dort habe ich einzelne Kanäle á 20A. 4 Kanäle für 100€ ist besser als 4x 65€ für den 1 EM Pro. Außerdem sind bei dem Shelly die Anschlüsse nicht gerade toll. Wenn der SPM die Summe liefert ist es ja kein Thema das Modell mit einzubinden.

**Comment by tomquist** [comment]
> -33 passt nicht, müsste +33 sein. Du erzeugst ja 33W?
> 
> Bei mehreren WR würde ich das einfach der DTU überlassen und die Summe daraus ziehen...

@reserve85 Das ist mir bei meinem Zwischenzähler auch aufgefallen, dass dort ein negativer Wert angezeigt wird. Macht ja auch Sinn. Es wird ja der Verbrauch gemessen und der ist bei den Zwischenzählern negativ. Macht es Sinn diesen Wert einfach als Absolut-Wert in die Berechnung einfließen zu lassen, unter der Annahme, dass ein Zwischenzähler einen Verbraucher haben sollte?

**Comment by reserve85** [comment]
Ja macht Sinn… vielleicht komm ich morgen dazu.
