### ISSUE TITLE
OpenDTU v24.2.16 und HoymilesZeroExport wollen nicht miteinander

### ISSUE THREAD

**Issue by robson1311** [reserve85/HoymilesZeroExport#148]
Hallo in die Runde!
Zur Info, zumindest war oder ist es bei mir so, dass die neueste Version (24.2.16) nicht mit diesem Script kommuniziert.
Hatte einiges durchprobiert und nur ein Downgrade auf meine vorige Version (24.1.4) hat das ganze gefixt.

Wie gesagt, bei einem Update auf die neueste OpenDTU könnte es Probleme geben!
LG Robert

**Comment by reserve85** [comment]
Korrekt, ihr müsst auf die neuste Script Version updaten dann funktioniert es auch mit der neuen OpenDTU Version.

**Comment by robson1311** [comment]
Ok, habe jetzt die py und die ini auf die neueste geupdatet, leider funktionierts aber so nicht.
Fehlermeldung:
Feb 24 14:47:41 Nulleinspeisung python3[20900]: 2024-02-24 14:47:41 INFO     OpenDTU: Inverter "HM1200" reachable: True
Feb 24 14:47:41 Nulleinspeisung python3[20900]: 2024-02-24 14:47:41 ERROR    Exception at GetHoymilesPanelMinVoltage, Inverter 0 not reachable

Werde wohl eine neue Komplettinstallation brauchen. Bin einstweilen wieder zurück auf die alte openDTU.

**Comment by reserve85** [comment]
Hast du das Script neu gestartet? Welche Version wird da angezeigt?

**Comment by Esojma-Silverbullet** [comment]
Das hat bei mir auch nicht funktioniert, neue saubere Installation hat es gebracht.
Dauert doch max. 10 Minuten.

**Comment by robson1311** [comment]
> Hast du das Script neu gestartet? Welche Version wird da angezeigt?

Version der ini 1.78, der py 1.79

**Comment by robson1311** [comment]
> Das hat bei mir auch nicht funktioniert, neue saubere Installation hat es gebracht. Dauert doch max. 10 Minuten.

da muss ich aber den ordner "hoymileszereoexport" löschen, mal sehen wie das geht.
