### ISSUE TITLE
Homeassistant 

### ISSUE THREAD

**Issue by strato345** [reserve85/HoymilesZeroExport#15]
Kann man das irgendwie in Homeassistant integrieren? Sorry ich hab da nicht so die Erfahrung

**Comment by reserve85** [comment]
Sorry aber nein, das geht nicht. Ist dafür auch nicht entwickelt worden. Es gibt zwar in HA eine Funktion für Pythonscripts, aber ich habe es kurz überflogen und das ist sehr eingeschränkt.
