### ISSUE TITLE
Limit inverters in battery mode first

### ISSUE THREAD

**Issue by tomquist** [reserve85/HoymilesZeroExport#151]
Ich betreibe das Script aktuell im gemischten Modus. Ein Inverter hat eine Batterie und der andere hat keine. In dieser Konstellation ist es aber so, dass die Batterie schon entladen wird, bevor die Inverter ohne Batterie ihre volle Kapazität ausgenutzt haben. Das Problem ist, dass die Wechselrichter Proportional zur Priorität limitiert werden.

Sollte stattdessen das Limit im gemischten Modus so verteilt werden, dass immer erstmal die Wechselrichter ohne Batterie de-limitiert werden und erst wenn diese ihr limit voll ausgenutzt haben, die Batterie-Wechselrichter de-limitiert werden?

Falls das Sinn ergibt erstelle ich gerne einen PR, wollte aber erstmal prüfen ob ich irgendetwas übersehen habe.

**Comment by reserve85** [comment]
Klingt für mich sinnvoll, allerdings habe ich zu Hause keinen Batteriebetrieb und kann da wenig dazu beitragen.
