### ISSUE TITLE
Docker Image Version

### ISSUE THREAD

**Issue by smaicloud** [reserve85/HoymilesZeroExport#153]
Kannst du dem Docker Image auch die Versionsnummer geben anstatt main?

**Comment by reserve85** [comment]
@tomquist ich hab da keine Ahnung von, kannst du das mal anschauen?

**Comment by reserve85** [comment]
ja wenn du mir sagst wie ich das mache, dann wäre das für mich kein Problem.
Ich bin hier quasi nur Hobby-User

**Comment by tomquist** [comment]
@reserve85 Ich habe einen PR erstellt. Sobald dieser gemerged ist, wird ein neuer Docker build angestoßen, sobald ein neuer Git tag erstellt (und gepushed) wird. Das Docker image wird dann immer sowohl mit dem Namen des Git-tags getagged, als auch mit `latest`.

**Comment by reserve85** [comment]
schaut so als als würde das klappen

![image](https://github.com/reserve85/HoymilesZeroExport/assets/111107925/afb9065b-ef36-4aac-ad1d-cd7efa9ff0d5)
