### ISSUE TITLE
Adding shell script support to query powermeter

### ISSUE THREAD

**Issue by bootix** [reserve85/HoymilesZeroExport#157]
I would like to use HoymilesZeroExport with a Victron Multiplus II. The Victron has multiple options to connect a power meter and can easily be queried by either MQTT oder Modbus TCP.

As neither protocol is implemented I would like to ask if it would be possible to add a shell script interface. So that HoymilesZeroExport executes that script which then queries the Victron or any other powermeter/inverter and returns the power value back to HoymilesZeroExport.

Thanks for checking,
dksoft

**Comment by bootix** [comment]
Done. Works well. I will provide code after some more testing.

**Comment by reserve85** [comment]
implemented in 1.85, thanks!
