### ISSUE TITLE
User/Password for Tasmota

### ISSUE THREAD

**Issue by jhedtmann** [reserve85/HoymilesZeroExport#159]
Hi, my Tasmota (Hichi) power meter demands user/password when querying the API. I have augmented the config and the constructor accordingly. If that is a common issue this should maybe go into the main dev branch...

**Comment by reserve85** [comment]
Hi,

currently user and password is not supported for tasmota webAPI, but it shouldn´t be a problem to implement it.
`http://<ip>/cm?user=<username>&password=<password>&cmnd=status%2010`
instead of 
`http://<ip>/cm?cmnd=status%2010`

i´ll add it soon and let you know.

**Comment by jhedtmann** [comment]
I can create a PR, if that is of any help. Its really a quite trivial
modification...

Thanks for your efforts!

Best, Jörg

**Comment by reserve85** [comment]
That would be great if you have already implemented it.
