### ISSUE TITLE
HM-1200 auf 1000 Watt begrenzen

### ISSUE THREAD

**Issue by robson1311** [reserve85/HoymilesZeroExport#166]
Hallo Leute,
ich möchte den Hoymiles 1200 bei Volllast auf 1000 Watt begrenzen.
Bisher läuft er bis max. 1200 Watt.
Habe schon einiges probiert, doch es bleibt bei den 1200 Watt in der openDTU.
Habe die  HOY_MAX_WATT = 1200 und die HOY_BATTERY_NORMAL_WATT = 1200 auf 1000 reduziert und ein Neustart vom Script, bzw. WR, nix.
MAX_DIFFERENCE_BETWEEN_LIMIT_AND_OUTPUTPOWER = 100 auf 90 runter, auch nix.
Würde mich über einen Tipp sehr freuen!
Danke schön

**Comment by reserve85** [comment]
Nimm die aktuelle Version, dann kannst du das so einstellen:

HOY_INVERTER_WATT = 1200
HOY_MAX_WATT = 1000
