### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by raffy1234** [reserve85/HoymilesZeroExport#173]
Sehr ärgerlich, es lief schon mal aber jetzt nach Umzug auf openDTU komme ich nicht wirklich weiter.

Mar 27 00:05:21 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 00:05:24 raspberrypi python3[819]: Traceback (most recent call last):
Mar 27 00:05:24 raspberrypi python3[819]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 00:05:24 raspberrypi python3[819]:     from packaging import version
Mar 27 00:05:24 raspberrypi python3[819]: ModuleNotFoundError: No module named 'packaging'
Mar 27 00:05:24 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 00:05:24 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 00:05:24 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 1.
Mar 27 00:05:24 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 00:05:24 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 00:05:25 raspberrypi python3[834]: Traceback (most recent call last):
Mar 27 00:05:25 raspberrypi python3[834]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 00:05:25 raspberrypi python3[834]:     from packaging import version
Mar 27 00:05:25 raspberrypi python3[834]: ModuleNotFoundError: No module named 'packaging'
Mar 27 00:05:25 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 00:05:25 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 00:05:25 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 2.
Mar 27 00:05:25 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 00:05:25 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 00:05:26 raspberrypi python3[835]: Traceback (most recent call last):
Mar 27 00:05:26 raspberrypi python3[835]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 00:05:26 raspberrypi python3[835]:     from packaging import version
Mar 27 00:05:26 raspberrypi python3[835]: ModuleNotFoundError: No module named 'packaging'
Mar 27 00:05:26 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 00:05:26 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 00:05:26 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 3.
Mar 27 00:05:26 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 00:05:26 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 00:05:26 raspberrypi python3[837]: Traceback (most recent call last):
Mar 27 00:05:26 raspberrypi python3[837]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 00:05:26 raspberrypi python3[837]:     from packaging import version
Mar 27 00:05:26 raspberrypi python3[837]: ModuleNotFoundError: No module named 'packaging'
Mar 27 00:05:27 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 00:05:27 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 00:05:27 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 4.
Mar 27 00:05:27 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 00:05:27 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 00:05:27 raspberrypi python3[839]: Traceback (most recent call last):
Mar 27 00:05:27 raspberrypi python3[839]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 00:05:27 raspberrypi python3[839]:     from packaging import version
Mar 27 00:05:27 raspberrypi python3[839]: ModuleNotFoundError: No module named 'packaging'
Mar 27 00:05:27 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 00:05:27 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 00:05:28 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 5.
Mar 27 00:05:28 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 00:05:28 raspberrypi systemd[1]: HoymilesZeroExport.service: Start request repeated too quickly.
Mar 27 00:05:28 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 00:05:28 raspberrypi systemd[1]: Failed to start HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 20:35:43 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 20:35:44 raspberrypi python3[3052]: Traceback (most recent call last):
Mar 27 20:35:44 raspberrypi python3[3052]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 20:35:44 raspberrypi python3[3052]:     from packaging import version
Mar 27 20:35:44 raspberrypi python3[3052]: ModuleNotFoundError: No module named 'packaging'
Mar 27 20:35:44 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 20:35:44 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 20:35:44 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 1.
Mar 27 20:35:44 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 20:35:44 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 20:35:44 raspberrypi python3[3055]: Traceback (most recent call last):
Mar 27 20:35:44 raspberrypi python3[3055]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 20:35:44 raspberrypi python3[3055]:     from packaging import version
Mar 27 20:35:44 raspberrypi python3[3055]: ModuleNotFoundError: No module named 'packaging'
Mar 27 20:35:44 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 20:35:44 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 20:35:45 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 2.
Mar 27 20:35:45 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 20:35:45 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 20:35:45 raspberrypi python3[3056]: Traceback (most recent call last):
Mar 27 20:35:45 raspberrypi python3[3056]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 20:35:45 raspberrypi python3[3056]:     from packaging import version
Mar 27 20:35:45 raspberrypi python3[3056]: ModuleNotFoundError: No module named 'packaging'
Mar 27 20:35:45 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 20:35:45 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 20:35:45 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 3.
Mar 27 20:35:45 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 20:35:45 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 20:35:46 raspberrypi python3[3057]: Traceback (most recent call last):
Mar 27 20:35:46 raspberrypi python3[3057]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 20:35:46 raspberrypi python3[3057]:     from packaging import version
Mar 27 20:35:46 raspberrypi python3[3057]: ModuleNotFoundError: No module named 'packaging'
Mar 27 20:35:46 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 20:35:46 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 20:35:46 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 4.
Mar 27 20:35:46 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 20:35:46 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 20:35:47 raspberrypi python3[3058]: Traceback (most recent call last):
Mar 27 20:35:47 raspberrypi python3[3058]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 20:35:47 raspberrypi python3[3058]:     from packaging import version
Mar 27 20:35:47 raspberrypi python3[3058]: ModuleNotFoundError: No module named 'packaging'
Mar 27 20:35:47 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 20:35:47 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 20:35:47 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 5.
Mar 27 20:35:47 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 20:35:47 raspberrypi systemd[1]: HoymilesZeroExport.service: Start request repeated too quickly.
Mar 27 20:35:47 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 20:35:47 raspberrypi systemd[1]: Failed to start HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 21:55:43 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 21:55:43 raspberrypi python3[3143]: Traceback (most recent call last):
Mar 27 21:55:43 raspberrypi python3[3143]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 21:55:43 raspberrypi python3[3143]:     from packaging import version
Mar 27 21:55:43 raspberrypi python3[3143]: ModuleNotFoundError: No module named 'packaging'
Mar 27 21:55:43 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 21:55:43 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 21:55:43 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 1.
Mar 27 21:55:43 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 21:55:43 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 21:55:44 raspberrypi python3[3144]: Traceback (most recent call last):
Mar 27 21:55:44 raspberrypi python3[3144]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 21:55:44 raspberrypi python3[3144]:     from packaging import version
Mar 27 21:55:44 raspberrypi python3[3144]: ModuleNotFoundError: No module named 'packaging'
Mar 27 21:55:44 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 21:55:44 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 21:55:44 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 2.
Mar 27 21:55:44 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 21:55:44 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 21:55:44 raspberrypi python3[3145]: Traceback (most recent call last):
Mar 27 21:55:44 raspberrypi python3[3145]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 21:55:44 raspberrypi python3[3145]:     from packaging import version
Mar 27 21:55:44 raspberrypi python3[3145]: ModuleNotFoundError: No module named 'packaging'
Mar 27 21:55:44 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 21:55:44 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 21:55:45 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 3.
Mar 27 21:55:45 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 21:55:45 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 21:55:45 raspberrypi python3[3146]: Traceback (most recent call last):
Mar 27 21:55:45 raspberrypi python3[3146]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 21:55:45 raspberrypi python3[3146]:     from packaging import version
Mar 27 21:55:45 raspberrypi python3[3146]: ModuleNotFoundError: No module named 'packaging'
Mar 27 21:55:45 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 21:55:45 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 21:55:45 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 4.
Mar 27 21:55:45 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 21:55:45 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 21:55:46 raspberrypi python3[3147]: Traceback (most recent call last):
Mar 27 21:55:46 raspberrypi python3[3147]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 21:55:46 raspberrypi python3[3147]:     from packaging import version
Mar 27 21:55:46 raspberrypi python3[3147]: ModuleNotFoundError: No module named 'packaging'
Mar 27 21:55:46 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 21:55:46 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 21:55:46 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 5.
Mar 27 21:55:46 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 21:55:46 raspberrypi systemd[1]: HoymilesZeroExport.service: Start request repeated too quickly.
Mar 27 21:55:46 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 21:55:46 raspberrypi systemd[1]: Failed to start HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 22:01:52 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 22:01:52 raspberrypi python3[3209]: Traceback (most recent call last):
Mar 27 22:01:52 raspberrypi python3[3209]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 22:01:52 raspberrypi python3[3209]:     from packaging import version
Mar 27 22:01:52 raspberrypi python3[3209]: ModuleNotFoundError: No module named 'packaging'
Mar 27 22:01:52 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 22:01:52 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 22:01:52 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 1.
Mar 27 22:01:52 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 22:01:52 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 22:01:53 raspberrypi python3[3210]: Traceback (most recent call last):
Mar 27 22:01:53 raspberrypi python3[3210]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 22:01:53 raspberrypi python3[3210]:     from packaging import version
Mar 27 22:01:53 raspberrypi python3[3210]: ModuleNotFoundError: No module named 'packaging'
Mar 27 22:01:53 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 22:01:53 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 22:01:53 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 2.
Mar 27 22:01:53 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 22:01:53 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 22:01:54 raspberrypi python3[3211]: Traceback (most recent call last):
Mar 27 22:01:54 raspberrypi python3[3211]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 22:01:54 raspberrypi python3[3211]:     from packaging import version
Mar 27 22:01:54 raspberrypi python3[3211]: ModuleNotFoundError: No module named 'packaging'
Mar 27 22:01:54 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 22:01:54 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 22:01:54 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 3.
Mar 27 22:01:54 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 22:01:54 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 22:01:54 raspberrypi python3[3212]: Traceback (most recent call last):
Mar 27 22:01:54 raspberrypi python3[3212]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 22:01:54 raspberrypi python3[3212]:     from packaging import version
Mar 27 22:01:54 raspberrypi python3[3212]: ModuleNotFoundError: No module named 'packaging'
Mar 27 22:01:54 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 22:01:54 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 22:01:55 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 4.
Mar 27 22:01:55 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 22:01:55 raspberrypi systemd[1]: Started HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 22:01:55 raspberrypi python3[3213]: Traceback (most recent call last):
Mar 27 22:01:55 raspberrypi python3[3213]:   File "/home/pi/HoymilesZeroExport/HoymilesZeroExport.py", line 33, in <module>
Mar 27 22:01:55 raspberrypi python3[3213]:     from packaging import version
Mar 27 22:01:55 raspberrypi python3[3213]: ModuleNotFoundError: No module named 'packaging'
Mar 27 22:01:55 raspberrypi systemd[1]: HoymilesZeroExport.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 22:01:55 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 22:01:55 raspberrypi systemd[1]: HoymilesZeroExport.service: Scheduled restart job, restart counter is at 5.
Mar 27 22:01:55 raspberrypi systemd[1]: Stopped HoymilesZeroExport.service - HoymilesZeroExport Service.
Mar 27 22:01:55 raspberrypi systemd[1]: HoymilesZeroExport.service: Start request repeated too quickly.
Mar 27 22:01:55 raspberrypi systemd[1]: HoymilesZeroExport.service: Failed with result 'exit-code'.
Mar 27 22:01:55 raspberrypi systemd[1]: Failed to start HoymilesZeroExport.service - HoymilesZeroExport Service.

wo habe ich einen Fehler gemacht?

**Comment by tomquist** [comment]
> No module named 'packaging'

Das deutet darauf hin, dass dir das Modul `packaging` fehlt. Versuche mal das:
```
pip3 install -r requirements.txt
```

**Comment by raffy1234** [comment]
> > No module named 'packaging'
> 
> Das deutet darauf hin, dass dir das Modul `packaging` fehlt. Versuche mal das:
> 
> ```
> pip3 install -r requirements.txt
> ```

Hat leider nicht funktioniert. Ich werde wohl Python komplett neu installieren müssen?!

**Comment by reserve85** [comment]
Muss gehen, hast du alle Dateien neu geladen?
 Ansonsten: 
pip3 install packaging

**Comment by raffy1234** [comment]
> Muss gehen, hast du alle Dateien neu geladen? Ansonsten: pip3 install packaging

Danke für die Info. Ich werde es probieren wenn ich wieder zu Hause bin.

**Comment by raffy1234** [comment]
Nach der Anleitung von lullatscho
https://github.com/reserve85/HoymilesZeroExport/issues/137 
hat es nun geklappt.
Vielen Dank für die tolle Hilfe hier.

**Comment by lullatscho** [comment]
Super dann hat die Anleitung ja schon jemanden geholfen
