### ISSUE TITLE
Lösung für 2 Inverter mit 2 Powermeter

### ISSUE THREAD

**Issue by sveba** [reserve85/HoymilesZeroExport#177]
Vielen Dank für die tolle Arbeit. 
Ich habe folgender UseCase:
2 Wohnungen/Powermeter mit je einem Inverter, aber einen einzigen AhoyDTU. Würde gern ZeroExport pro Wohnung einrichten.

Was habe ich versucht:
- Config durchgelesen - keine Lösung gefunden
- Zweite Instanz mit je nur einem Inverter und manueller Eingabe von SERIAL_NUMBER - kein Erfolg

Kann man irgendwie steuern, welcher Inverter überhaupt limitiert wird? Für mich würde es reichen, wenn ich zwei Instanzen vom Script starten kann, mit zwei konfigurierten Inverter, aber dann entsprechend den einen immer ignorieren :)

Danke für eure Tipps

**Comment by tomquist** [comment]
@reserve85 Sollte sich das nicht relative leicht unterstützen lassen indem man für jeden Inverter optional den AhoyDTU index setzen kann? Alternativ könnte man das Mapping auch automatisch über die SERIAL_NUMBER config ermitteln. Eventuell übersehe ich auch etwas.

**Comment by reserve85** [comment]
hast aber zwei Stromzähler etc?
