### ISSUE TITLE
Kleiner Bug in der Benennung der Logdatei

### ISSUE THREAD

**Issue by Ollipop030** [reserve85/HoymilesZeroExport#18]
Guten Morgen,

nur ein Hinweis: Die aktuelle Logdatei heißt da immer today.log, diese wird irgendwann Nachts anscheinend umbenannt, die Datei von gestern heißt aber 20230324_000011, der ist aber heute. 😄

**Comment by reserve85** [comment]
Nehm ich mit.

**Comment by reserve85** [comment]
Sollte behoben sein
