### ISSUE TITLE
Shelly em value problem 2 probes

### ISSUE THREAD

**Issue by pierre673** [reserve85/HoymilesZeroExport#181]
Good morning
I installed your script with a shelly em 2 probes.
1 probe for consumption coming from the network and 1 probe for the production of solar panels.
the problem is that the script adds the 2 values.
example :
my network indicates -300w on probe 1 and 1500w production on probe 2. the value taken by the script is 1200w.
It should only take the value of probe 1.
Is there a solution ?
THANKS

**Comment by reserve85** [comment]
Hi,

good idea, i´ll take a look into this topic in the next days.

**Comment by reserve85** [comment]
i added it into the "dev" branch: https://github.com/reserve85/HoymilesZeroExport/tree/dev
would be nice if you can test it before i merge it into the main branch?

**Comment by pierre673** [comment]
Great, it works.
Just wait for the sun.
Now I have to figure out how to install it on my docker NAS.
Because for the moment the script works on a Linux virtual machine.

**Comment by reserve85** [comment]
perfect, i´ll copy it into the main branch!
