### ISSUE TITLE
Gesendete Limits werden am Wechselrichter nicht angenommen

### ISSUE THREAD

**Issue by PolyGONtrauma** [reserve85/HoymilesZeroExport#19]
Hallo!

Vorab vielen Dank für deine Arbeit!
Ich weiß nicht ob der Fehler am Skript liegt, hoffe aber hier eine Lösung zu finden: Das Skript läuft bei mir ohne Fehlermeldungen über OpenDTU, Shelly3EM und 3 Wechselrichter (2x HM1500, 1x HM800). Auslesen der Wechselrichter und des Shelly3EM klappt laut Log einwandfrei, aber die gesetzten Limits werden bei den Wechselrichtern nie angenommen.
Woran könnte das liegen? Fehler bekomme ich keine angezeigt.

**Comment by PolyGONtrauma** [comment]
Danke für die Tipps! Habe zum Testen einerseits die Wartezeit zwischen den Limitbefehlen angehoben und andererseits auch mal zwei Wechselrichter entfernt, um nur mit einem testen zu können - beides ohne Erfolg.
Aus dem Log in OpenDTU werde ich leider nicht schlau.
Eine Vermutung habe ich allerdings noch, OpenDTU lässt die Abfrage ohne Passwort zu, zum Schreiben des Limits wird das Passwort aber benötigt - vielleicht hängt es irgendwie daran? Immerhin ist das Passwort in OpenDTU und der Script-Config identisch.

**Comment by reserve85** [comment]
Top, danke für deine Rückmeldung und freut mich auch, dass es funktioniert. 
Ja, die Abfrage geht bei openDTU ohne Seriennummer, das erklärt es dann natürlich.

Dann kann ich hier zu machen?
