### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by clajog** [reserve85/HoymilesZeroExport#195]
Hallo,

als Neuling im Bereich Linux - Wo finde ich die Logs?

**Comment by reserve85** [comment]
Du kannst das aktuelle Journal anschauen mit

sudo journalctl -u HoymilesZeroExport.service -n 20000 -e -f

oder in der config das "Logging" aktivieren, dann wird das in den unterordner "Logs" gespeichert.

**Comment by clajog** [comment]
Danke schön,
