### ISSUE TITLE
SELECT_INTERMEDIATE_METER to be a script ?

### ISSUE THREAD

**Issue by Thierry43** [reserve85/HoymilesZeroExport#197]
Hello,
Would it be possible to add the option to use a script as an intermediate meter ?
I currently use a script as a power-meter to read power value from a MSunPV power router (https://ard-tek.com/). 
I would also like to use the PV power value read from the same device. 

Thanks in advance !

Thierry

**Comment by Thierry43** [comment]
Great ! I will test it tomorrow. 
Just one more question: Must the intermediate meter value be positive or negative ? 

If you want to add my scripts to get data from a MsunPV Solar Power Diverter from https://ard-tek.com/ you can find them below:

-----------
#! /bin/bash
# Script to read powermeter values from a MSunPV (ard-tek.com)
IFS=";"
#Grid power
AC_GRID=$(curl -s http://MSunPV_IP/status.xml | tail -n 3 | (read var1 var2 var3; echo ${var1:7:20}))
echo ${AC_GRID%%,*}
------------------------------
#! /bin/bash
# Script to read PV Solar power values from a MSunPV (ard-tek.com)
IFS=";"
#PV Solar power
AC_PV=$(curl -s http://MSunPV_IP/status.xml | tail -n 3 | (read var1 var2 var3; echo ${var2}))
echo ${AC_PV%%,*}
--------------------------------

**Comment by reserve85** [comment]
> Great ! I will test it tomorrow. Just one more question: Must the intermediate meter value be positive or negative ?

Doesn’t care if pos or neg, it’s converted to an absolute value.

**Comment by Thierry43** [comment]
> > Great ! I will test it tomorrow. Just one more question: Must the intermediate meter value be positive or negative ?
> 
> Doesn’t care if pos or neg, it’s converted to an absolute value.

Perfect ! Thanks a million for your great work ;-)

**Comment by reserve85** [comment]
Does everything work for you? Then I would add the scripts to the repository…

**Comment by Thierry43** [comment]
Everything is working fine !
