### ISSUE TITLE
Toleranzen

### ISSUE THREAD

**Issue by mark82436** [reserve85/HoymilesZeroExport#20]
Hallo 

ich hätte mal eine Frage zu den Toleranzen.
Da im Moment das Wetter/Wolken dauernd hin und her ziehen ist das ganze auf dem Powermeter
ziemlich unruhig und ich wollte das ganze etwas softer einstellen, dass nicht die ganze Zeit hin und her geregelt wird.

Wenn ich die Werte unter Control verändere, z.B.
POWERMETER_TARGET_POINT = -100
POWERMETER_TOLERANCE = 50
POWERMETER_MAX_POINT = 100

Dann müsste das ganze doch etwas träger werden oder muss man da noch etwas anderes beachten?

**Comment by reserve85** [comment]
Ja, dann regelt er zwischen -150W und -50W gar nicht und ab +100W springt er sofort! auf 100%. Wenn es die Werte allerdings sekündlich schwanken und auch teilweise über 100W, dann regelt er ständig auf 100%. Bei so einem Wetter bekommst du das nicht „smooth“ hin.
