### ISSUE TITLE
Problem to start the script

### ISSUE THREAD

**Issue by Sebastian7902** [reserve85/HoymilesZeroExport#215]
<img width="908" alt="Screenshot 2024-06-23 023041" src="https://github.com/reserve85/HoymilesZeroExport/assets/84236344/0a66b713-d59a-49d4-9f32-182717a9851b">

**Comment by reserve85** [comment]
https://github.com/reserve85/HoymilesZeroExport/issues/137

**Comment by tomquist** [comment]
@reserve85 I think we can fix this by requiring an older version of the `packaging` module in `requirements.txt`. Version 21.3 still supports python 3.6 so we could require `packaging` to be `>=21.3`.

**Comment by tomquist** [comment]
Maybe it's just time to ditch support for Python <= 3.7. They all reached their end-of-life: https://devguide.python.org/versions/
