### ISSUE TITLE
Trucki2meanwellgateway T2MG direkt im Script einbinden?

### ISSUE THREAD

**Issue by tclv2000** [reserve85/HoymilesZeroExport#220]
Ich lade einen Powerqueen Akku mit einem Menawell Ladegerät. Dieses Ladegerät wird über den T2MG Stick und den Shelly 3 EM geregelt.  Außerdem läuft Dein Script zur Nulleinspeisung i.  V. m. mit ein Paar Regelungen über Openhab via MQTT.

Ist eine direkte Anbindung des T2MG an das Script möglich?

Solange die maximale Ladeleistung des Meanwell-Ladegerätes nicht erreicht ist, wird dann nicht runtergeregelt? Quasi als fiktives Plus auf den Targetpoint bis das Ladegerät die maximale Leistung hat?

Regele das aktuell zwar lauffähig über MQTT/Openhab, jedoch ist der zeitliche Versatz entsprechen lang.

Wäre es möglich, bevor das Script die Leistung Richtung Targetpoint runterregelt, den ACSetpoint des T2MG entsprechend des vorhandenen Überscnhusses per MQTT zu setzen bis die maximale Ladesleitung des Meanwell-Laderäteds erreicht ist  und dann erst die Regelung auf den Targetpoint auszulösen?

**Comment by reserve85** [comment]
Hi,

out of the Box würde ich sagen dass der Anwendungsfall eher etwas für HomeAssistant o.Ä ist. 
Dort kannst du den Targetpoint des Scripts anpassen, solange dein Ladegerät noch lädt. 
Du machst das schon via Openhab? Was meinst du mit zeitlicher Versatz?

**Comment by tclv2000** [comment]
Mit dem zeitlichen Versatz meinte ich die Verabeitungszeit bis sich meine 4 HM600 wieder auf den Targetpoint eingependelt haben. Außerdem standen sich die Regelung des Ladegrätes und die Regelung der Inverter immer irgendwie im Weg.

Mein Gedanke war, dass die Regelung des Scriptes erst beginnt, wenn das Ladegerät seine maximale Leistung liefert.

Die Lösung war nicht die Anpassung des Targetpoints über MQTT, sondern die Anpassung der minimalen Inverterleistung. Solange das Ladegerät seine maximale Leistung nicht erreicht, setze ich die minimale Inverterleistung auf 100% und das T2MG übernimmt die Regelung auf den dort gesetzten Targetpoint. Bei erreichen der maximalen Leistung des Ladegerätes wird der Wert wieder auf 5% gesetzt und die Regelung auf den Targetpoint des Scripts setzt ein.
