### ISSUE TITLE
Max und Min Einspeisung Jump

### ISSUE THREAD

**Issue by filou01** [reserve85/HoymilesZeroExport#248]
Hallo. 

Ich hab die Vermutung, dass bei Überschreitung des  POWERMETER_MAX_POINT der Jump (ON_GRID_USAGE_JUMP_TO_LIMIT_PERCENT = 100) sofort ausgeführt wird, und nicht erst beim nächsten LOOP_INTERVAL. Kann dies so stimmen?

Im umgekehrten Fall, wo durch zu wenig Eigenverbrauch der 
POWERMETER_MIN_POINT unterschritten wird, scheint es aber ob der Jump (ON_GRID_FEED_FAST_LIMIT_DECREASE) erst beim nächsten LOOP_INTERVAL ausgeführt wird und somit in meinem Fall eine Überschreitung der zulässigen 800W Einspeisung für 20 Sekunden möglich ist. 

Sehe ich das richtig? 

Danke und Lg

**Comment by reserve85** [comment]
Ne, das ist in der gleichen Schleife und wird ebenfalls sofort ausgeführt (identisch zu on_grid_usage_jump_to_limit_percent).

Allerdings ist innerhalb der 20s (LOOP_INTERVAL_IN_SECONDS) nur eine Operation möglich.

**Comment by filou01** [comment]
Danke für die Erklärung
