### ISSUE TITLE
Inverternamen/Temperatur im Log anzeigen

### ISSUE THREAD

**Issue by Ollipop030** [reserve85/HoymilesZeroExport#38]
Kann man den Inverter über das Script beim Namen nennen? In Ahoy vergibt man ja Namen für die Inverter, diesen Namen könnte man ja auch im Script anzeigen lassen. Sieht ein bisschen hübscher aus als Inverter 0, Inverter 1...

Des Weiteren:
Der HM1500 wird sehr warm bei mir. Ist außen montiert, Nordseite an der Wand, auf 100% Limit komme ich aber schnell an die 45 Grad. Kann man die Temperatur mit abrufen, so dass die mit geloggt wird? Meine Idee für die Zukunft wäre dann vielleicht eine Art Sicherheitsfunktion, das bei Überschreiten einer bestimmten Temperatur die Leistung gedrosselt wird. Das funktioniert auch tatsächlich, sobald ich manuell die Leistung limitiere wird der WR auch wieder kühler. Nur hätte ich gern die Möglichkeit überhaupt die Temperatur mitzuschreiben, die hohen Außentemperaturen kommen ja erst noch, wobei der HM1500 glaub ich bis 60 Grad ab kann.

BTW:
Eigentlich wollte ich die Log Dateien nur 5 Tage behalten, ich habe aber jetzt schon 8 Files. Kann es sein, dass der Counter dafür wieder neu startet, sobald auch der Dienst neu gestartet wird?

**Comment by reserve85** [comment]
Servus, den Namen könnte ich aus Ahoy / openDTU auslesen. Schau ich mir mal an. Die Temperatur dann ebenfalls, wobei ich das nur optional machen würde, da extra Abfrage. Ich nehm es mal mit wenn ich Zeit habe. 

Bzgl Log müsste ich das mal testen, kann aber durchaus sein dass das so ist. Wenn das die benutzte Library nicht hergibt dann lass ich es auch so, selber will ich da nix programmieren.

**Comment by Ollipop030** [comment]
> Allerdings hat der Hoymiles selbst eine „Notdrosselfunktion“ bei Überhitzung. Habe ich irgendwo mal gelesen.

Das stimmt. Aber ich dachte, er schaltet dann komplett ab. Naja, wie auch immer, erstmal das lange Wochenende genießen.

**Comment by reserve85** [comment]
https://github.com/reserve85/HoymilesZeroExport/tree/dev

**Comment by Ollipop030** [comment]
Hi, grad installiert bekomme noch folgendes im Log:

```
Apr 08 16:38:49 raspberrypi python3[13615]: 2023-04-08 16:38:49 INFO     Ahoy: Inverter "HM-300" reachable: True
Apr 08 16:38:49 raspberrypi python3[13615]: [74B blob data]
Apr 08 16:38:49 raspberrypi python3[13615]: [73B blob data]
```

Wird wahrscheinlich die Temperatur Abfrage sein?

**Comment by reserve85** [comment]
Äh im logfile oder im Live log? Bei mir kommt das nicht?

**Comment by Ollipop030** [comment]
Komisch. Nur im Live Log. Im Logfile steht die Temperatur.

**Comment by reserve85** [comment]
Hab eine Vermutung: kannst du mal im Code die „°C“ in „degC“ ändern? Ggf. kann das Terminal das bei dir nicht ausgeben

**Comment by Ollipop030** [comment]
Ja kommt was:

`Ahoy: Inverter "HM-1500" temperature: 25.0 degC`

**Comment by reserve85** [comment]
Ok dann ändere ich das noch, danke

**Comment by Ollipop030** [comment]
Unter Windows funktioniert das übrigens in der ursprünglichen Form. Anscheinend mag Linux das Gradzeichen nicht.

**Comment by reserve85** [comment]
Ja komisch, bei mir im raspi ging es auch, debian system

**Comment by Ollipop030** [comment]
Bin auf Raspian Buster, aber basiert ja auf Debian. Eigenartig.

**Comment by reserve85** [comment]
OK, habs in der MAIN angepasst. Die Logfiles musste ich als Default-Benamung lassen, dann werden die automatisch gelöscht.

**Comment by Ollipop030** [comment]
Vielen Dank. Das Gradzeichen wird wohl bei mir nicht funktionieren, da die Shell bei mir deutsch ausgibt. Wird wohl ein anderer Zeichensatz installiert sein. War damals ein offizielles Raspi Image, nur eben auf deusch.
