### ISSUE TITLE
Inverter Abfragelogik funktioniert nicht mehr mit OpenDTU

### ISSUE THREAD

**Issue by onceuponatime78** [reserve85/HoymilesZeroExport#39]
Hi,
hab heute morgen ein update auf den aktuellen Stand gemacht und festgestellt, dass durch "if USE_AHOY:" in Zeile 146 die Logik mit OpenDTU nicht mehr funktioniert und die Inverter nicht mehr abgefragt werden - hab daher die Zeile bei mir entfernt und es funktioniert wieder

**Comment by reserve85** [comment]
Ich hab das heute morgen auch entdeckt und schon lokal gefixt, ich checke es nachher ein. Danke für den Hinweis.

**Comment by reserve85** [comment]
Sollte gefixt sein in der DEV Version:
https://github.com/reserve85/HoymilesZeroExport/tree/dev
