### ISSUE TITLE
Wie mache ich ein Update 

### ISSUE THREAD

**Issue by strato345** [reserve85/HoymilesZeroExport#46]
Hallo habe es geschafft nach langen Versuchen das Script zu installieren. Funktioniert auch sehr sehr gut. Vielen Dank für deine Arbeit.
Wie Date ich jetzt genau auf die neue Version ab ? Einfach mit install.sh wie bei der Installation? Wird die Config dabei  überschrieben? 
gibt es eigentlich eine Erklärung zu den einzelnen Einstellung ein in der Config? Mir ist die ganze Wirkungsweise nicht ganz klar. In Homeassistant kann ich aber gut sehen wie das Skript meine WRs regelt und es an meinen tatsächlichen Verbrauch angleicht. Um das zu optimieren und zu verstehen brauche ich aber eine etwas genauere Erklärung. 

Sorry ich bin über 50 und ha eigentlich gar keine Programmierkenntnisse

**Comment by reserve85** [comment]
Hi,

freut mich, dass soweit alles klappt. Es ist halt ein "einfaches" Script und kein automatisch updatefähiges Paket, somit musst du das Update "leider" selbst durchführen. 

ich gehe so vor:

Terminal öffnen
`cd HoymilesZeroExport`
`sudo nano HoymilesZeroExport.py`
in die 1. Zeile 1.Buchstabe springen
`ALT+A`
danach mit 
`ALT+DOWN`
bis zum Ende springen und alles dadurch markieren
dann mit 
`STRG+K`
alles ausschneiden
dann den neuen Inhalt der neuen Datei kopieren und mit rechtsklick ins terminal einfügen
speichern mit
`STRG+S`
beenden mit
`STRG+X`

Für die Config das gleiche, die Werte vorher quick and dirty abfotografieren. 

Zum Schluss dann mit
`sudo ./restart`
das Script neu starten.

Hoffe das klappt so auch bei dir. Alternativ kannst du auch einfach neu installieren (vorher die config sichern für die Einstellungen), da musst du aber den Ordner HoymilesZeroExport am besten vorher löschen.
Für die Regelparameter und Einstellungen schau mal hier rein:
https://github.com/reserve85/HoymilesZeroExport/issues/28
