### ISSUE TITLE
Keine Daten vom Tasmota Sensor

### ISSUE THREAD

**Issue by keinprofi** [reserve85/HoymilesZeroExport#48]
Hi,

geniales Projekt, nur für mich leider zu schwer....

Ich habe alles soweit auf meinem RasPi installiert und "einiges" funktioniert auch. Bis auf die Verbindung mit dem Tasmota Sensor (Hichi WLAN). 
Bilder sagen mehr als 1000 Worte:
Der Tasmota Hichi WLAN Sensor (unabhängig vom System im Browser):
![Tasmota](https://user-images.githubusercontent.com/131543857/233798428-b127e946-78f8-4c57-ae64-878bf44b5bfc.jpg)
Der zeigt natürlich auch negative Werte an wenn ich einspeise.

Der Raspi:
![Raspi](https://user-images.githubusercontent.com/131543857/233798434-486384bd-286f-422a-a8b1-7c72705a2124.jpg)

Wie bekomme ich das Script nun dazu den aktuellen Verbrauch sauber auszulesen, damit die WR entsprechend angepasst werden können?

Beste Grüße
Ka.

**Comment by reserve85** [comment]
Hi, das kriegen wir schon hin:
Gib mal bitte das hier im Browser ein und teile bitte das result: http://xxx.xxx.xxx.xxx/cm?cmnd=status%2010

Natürlich mit der korrekten IP von tasmota.
Und kannst du die IP auch von dem RasPi pingen?

**Comment by keinprofi** [comment]
Raspi kann ich ohne weiteres erreichen. 
Beim Link oben bekomme ich File not found.

Muss ich die Raspi IP in der Config irgendwo angeben? Hab da nichts gesehen.

**Comment by reserve85** [comment]
Die xxx hast du auch geändert? Zur tasmota IP?

**Comment by keinprofi** [comment]
klar doch.
Aber ich habe mich vertippt, sorry...

![link_crop](https://user-images.githubusercontent.com/131543857/233799364-d4daac87-bacb-40bb-b5b7-bc34c8ae5a21.jpg)

**Comment by keinprofi** [comment]
![grafik](https://user-images.githubusercontent.com/131543857/233799455-16521ae3-0938-467f-ac39-05f2202b8e90.png)

**Comment by reserve85** [comment]
ok, aber ist ja aktiv wenn du da was zurückbekommst.
Du musst in der Config einstellen:

```
[TASMOTA]
...
TASMOTA_IP = xxx.xxx.xxx.xxx
TASMOTA_JSON_STATUS = StatusSNS
TASMOTA_JSON_PAYLOAD_MQTT_PREFIX = Strom
TASMOTA_JSON_POWER_MQTT_LABEL = current
...
```

**Comment by keinprofi** [comment]
Die Daten bekommt er jetzt :-)
![grafik](https://user-images.githubusercontent.com/131543857/233799948-175d2b60-9fb2-4644-a22e-3d3b11a4feab.png)
sind die verbliebenden Fehler relevant? Der Sendor ist erreichbar (10.10.10.139) aber trotzdem Fehler?

**Comment by reserve85** [comment]
ja, das ist nicht so gut. Hast du am Tasmota eine schlechte WLAN Verbindung? kannst du mal über das Terminal über längere Zeit den Tasmota anpingen?

**Comment by keinprofi** [comment]
naja, der hängt leider in der Nachbarwohnung bei meinem Vermieter. Allerdings ein Repeater direkt im Zählerschrank (aus Metall...).
![grafik](https://user-images.githubusercontent.com/131543857/233800190-2888e81f-ad81-48a8-a10a-c9d3a4cbca79.png)

**Comment by keinprofi** [comment]
Ich bin gespannt auf Morgen wenn wieder Sonne da ist.

Dir auf jeden Fall mal tausend Dank!!!

**Comment by reserve85** [comment]
ja da ist dennoch ein Problem, du hast teilweise über 100ms für einen einfachen Ping und auch da bereits zwei mal Zeitüberschreitung... Musst du einfach mal beobachten, eventuell kannst du den repeater ja noch etwas optimieren.

**Comment by keinprofi** [comment]
OK, ich werde es mal versuchen. Mal sehen was geht.

**Comment by reserve85** [comment]
vielleicht hast du auch durch die Zählerschranktür den schlechten Empfang

**Comment by keinprofi** [comment]
da gehe ich von aus. ABer da der Repeater ja an meine Steckdose im Zählerschrank muss und außen kein Platz für den Repeater ist, könnte ich höchstens externe Antennen an den Repeater anbringen und die nach außen verlegen. Ist ein AVM 1200, muss ich erstmal nach Material gucken.
