### ISSUE TITLE
Homeassistant integrieren?

### ISSUE THREAD

**Issue by strato345** [reserve85/HoymilesZeroExport#50]
Könnte man Homeassistant ähnlich wie iobroker integrieren?

**Comment by reserve85** [comment]
Ja müsste gehen, werd ich die Tage mal versuchen.

**Comment by reserve85** [comment]
Habe es vorerst in die DEV eingecheckt. Wäre super wenn du es auch testen könntest, bei mir funktioniert es.
https://github.com/reserve85/HoymilesZeroExport/tree/dev
