### ISSUE TITLE
Frage zu SLOW_APPROX_LIMIT_IN_PERCENT

### ISSUE THREAD

**Issue by Ollipop030** [reserve85/HoymilesZeroExport#53]
Hi,

kann man SLOW_APPROX_LIMIT_IN_PERCENT und SLOW_APPROX_FACTOR_IN_PERCENT auf 0 setzen? Verstehe ich das richtig, wenn beide Werte 0 sind springt das Script direkt auf den Zielwert?

Oder muss SLOW_APPROX_LIMIT_IN_PERCENT auf 100 stehen für größtmögliche Sprünge?

**Comment by reserve85** [comment]
SLOW_APPROX_LIMIT_IN_PERCENT muss auf 100 stehen zum Deaktivieren.

**Comment by Ollipop030** [comment]
Danke für die schnelle Antwort. Das Glätten dauert bei meinem zeitverzögerten Zähler leider ziemlich lang, das versuche ich grad etwas zu kompensieren.
