### ISSUE TITLE
Überschusseinspeisung wenn Unterkapazität im Netz ist

### ISSUE THREAD

**Issue by XpertXXL** [reserve85/HoymilesZeroExport#60]
Man könnte doch, wenn "Strommangel" im Netz besteht (Netzfrequenz < 50Hz oder einer noch zu definierenden Frequenz) die Nulleinspeisung aufheben, um das Netz zu unterstützen.
Ist so was progammiertechnisch einfach umsetzbar??
Der WR stellt die aktuelle Netzfrequenz zur Verfügung.
Ich möchte das Netz nicht unnötig belasten, deshalb habe ich die Nulleinspeisung aktiviert und nicht, weil ich nichts verschenken will. Wenn es (hoffentlich) immer mehr werden, die ein BKW betreiben, verstehe ich die Sorgen der Netzbetreiber schon, dass das Netz schwieriger zu managen ist.
An dieser Stelle auch mein herzlicher Dank an reserve85 für das toll funktionierende Script.

XpertXXL

**Comment by Ollipop030** [comment]
Finde ich unnötig, denn die Netzbetreiber greifen ab 49,8Hz schon selbst ein. Glaube auch nicht das du mit deinem BKW da viel helfen würdest.
Übrigens: Das Netz belastest du gar nicht, denn der Strom, den du nicht verbrauchst wird beim Nachbarn verbraucht (Strom nimmt immer den kürzesten Weg).
