### ISSUE TITLE
Fernstart

### ISSUE THREAD

**Issue by strato345** [reserve85/HoymilesZeroExport#62]
wäre es möglich das Skript, z.b. durch Homeassistant ein oder ausschalten zu lassen? beim Ausschalten sollte es vorher die WR auf 100% stellen

**Comment by reserve85** [comment]
Das kannst du mit einem Bash-Script mit CURL Aufruf realisieren.
1. Script stoppen `systemctl stop HoymilesZeroExport.service`
2. CURL Aufruf zu AHOY/OpenDTU und Limit auf 100% setzen (https://codefather.tech/blog/curl-bash-script/)
3. Alternativ zu CURL: Das Limit setzen direkt aus HA

zum Starten wieder `systemctl start HoymilesZeroExport.service`
