### ISSUE TITLE
intermediate meter

### ISSUE THREAD

**Issue by fatzo** [reserve85/HoymilesZeroExport#65]
Moin zusammen
Damit sind ja die zwischenzähler gemeint.

Ich habe pro Solarstrang je einen Shelly 1PM dazwischen,

wie bringe ich beide in die Config?

**Comment by reserve85** [comment]
Hi,
geht so erstmal nicht - es ist nur ein Gesamtzähler als Zwischenzähler vorgesehen. 
Als option könntest du die Leistung der 1PM Shellys mittels HomeAssistant / IO Broker aufaddieren und den Gesamtwert dann als Intermediate meter auszulesen.

**Comment by fatzo** [comment]
> Hi, geht so erstmal nicht - es ist nur ein Gesamtzähler als Zwischenzähler vorgesehen. Als option könntest du die Leistung der 1PM Shellys mittels HomeAssistant / IO Broker aufaddieren und den Gesamtwert dann als Intermediate meter auszulesen.

**Comment by fatzo** [comment]
Vielen dank das hat mir geholfen.
