### ISSUE TITLE
Schritt für Schritt Anleitung für Windows 

### ISSUE THREAD

**Issue by tthnn** [reserve85/HoymilesZeroExport#67]
Hi . Wäre es dir möglich mal eine Schritt für Schritt Anleitung für Windows zu machen ? 
leider krieg ich das Script nach wie vor nicht zum laufen . Er findet immer die config nicht zumindest versucht er sich mit tasmota zu verbinden obwohl ich dort false und
Bei Shelly True geschrieben habe . 
toll wäre mal eine Anleitung

**Comment by tthnn** [comment]
![A806CBCB-6591-42C6-BC73-DFC78A0D1537](https://github.com/reserve85/HoymilesZeroExport/assets/130739445/b143d861-365d-47d5-9e57-8a4785463c9b)
![C2CAE422-BF55-46B5-B552-E3E4779473E0](https://github.com/reserve85/HoymilesZeroExport/assets/130739445/63df1326-b64c-425c-9fc9-f250287218f9)
![4EB01508-DFF4-42FE-863B-879D7F4A1668](https://github.com/reserve85/HoymilesZeroExport/assets/130739445/721087ff-99ea-49da-8aed-1bdcc3461dc9)
![CAB9FAE5-ADDD-4DCA-BD9B-05E2417C0C50](https://github.com/reserve85/HoymilesZeroExport/assets/130739445/03564e31-f71a-4c69-8545-98365eef7385)
![C644B34E-7746-4424-877A-2317409A9AA6](https://github.com/reserve85/HoymilesZeroExport/assets/130739445/255002c6-91cc-4b13-891c-6542384cc4c4)
![192264D9-D212-4FCA-804A-CB4B8B8209F4](https://github.com/reserve85/HoymilesZeroExport/assets/130739445/c3aaa4a7-1ab7-4c5e-91fd-dfa08c0b9553)

**Comment by tthnn** [comment]
Beim Start des Skriptes schließt es sich sofort wieder .

**Comment by tthnn** [comment]
Und editieren tuh ich die Konfiguration Datei mit dem Edition

**Comment by reserve85** [comment]
Du hast bei [COMMON] / INVERTER_COUNT = 2 eingegeben aber unten nur ein Inverter konfiguriert. Ändere das auf 1 oder füge den zweiten Inverter am Ende hinzu.

**Comment by tthnn** [comment]
Ahh jetz gehts . Aber den zweiten Inverter will ich natürlich zufügen . Wie meinst du jetz den zweiten unten zu fügen ?

**Comment by reserve85** [comment]
ahso, jetzt sehe ich es.
ganz unten sind die ";" vor den Zeilen, das bedeutet "auskommentiert" - entferne die Semikolons und dann sollte es laufen.
