### ISSUE TITLE
einstellung Netzverbrauch

### ISSUE THREAD

**Issue by fatzo** [reserve85/HoymilesZeroExport#71]
moin zusammen
Was muss ich genau einstellen bei 2 hoymiles damit der Netzverbrauch immer um die 50 Watt liegt?

fruß fatzo

**Comment by reserve85** [comment]
Genau, aber bitte auch nicht vergessen den POWERMETER_MAX_POINT anzupassen, z.B. dann auf 125 (muss höher sein als TargetPoint + Toleranz).
Sonst kommt er gar nicht in die "richtige" Regelschleife sondern hängt in der "Sofort-Reagieren"-Regelung fest. Funktioniert zwar auch, aber nicht so gut.
Also: POWERMETER_TARGET_POINT + POWERMETER_MAX_POINT anpassen.
