### ISSUE TITLE
OpenDTU mit HMS Wechselrichter

### ISSUE THREAD

**Issue by mark82436** [reserve85/HoymilesZeroExport#73]
Hallo Tobi,

ich wollte Dir Rückmeldung geben ich habe jetzt seit 3 Wochen
Dein Script mit einer OpenDTU-S und 2 Hoymiles Wechselrichter der HMS Serie (1x HMS-1800, 1x HMS-2000) am Laufen.
Habe gerade auf 1.39 umgestellt, läuft ohne Probleme.

Besten Dank für das tolle Script!

**Comment by mark82436** [comment]
Eine Frage hätte ich noch dazu.

Ich betreibe die 2 WR an 2 Phasen mit jeweils einem Tasmota Zwischenstecker, gibt es die Möglichkeit
im Script auch mit 2 Tasmota Zwischenzählern zu arbeiten?

**Comment by reserve85** [comment]
Nee gibts nicht, aber du kannst beide Werte z.B. in HomeAssistant oder ioBroker zusammenfassen und darüber drauf zugreifen. Es läuft aber auch sehr gut ohne Zwischenzähler.

**Comment by mark82436** [comment]
ok danke für die Rückmeldung, dann lasse ich die Zwischenzähler weg
läuft auch so ganz gut, nur mit der OpenDTU als Zähler.
