### ISSUE TITLE
Beschreibungen in der HoymilesZeroExport_Config.ini Version 1.44

### ISSUE THREAD

**Issue by Ollipop030** [reserve85/HoymilesZeroExport#83]
Hi,

grad mal die neue Version angesehen. In der *.ini sollte noch Zeile 208 bearbeitet werden:

_if JUMP_TO_MAX_LIMIT_ON_GRID_USAGE = true, then the limit will jump to 100% by reaching this point._

JUMP_TO_MAX_LIMIT_ON_GRID_USAGE gibt es ja nicht mehr.

Außerdem noch die Zeile 261, da das gleiche.

**Comment by reserve85** [comment]
Passe ich in der nächsten Version mit an, danke!!
