### ISSUE TITLE
Home Assistent-Automation

### ISSUE THREAD

**Issue by Mart-Muc** [reserve85/HoymilesZeroExport#9]
Servus,

prima script, aber bevor ich das auf meinem hassio installier, wäre mir eine Home Assistent-Automation lieber.

Könntest Du sowas dauraus basteln?

Danke, Mart

**Comment by reserve85** [comment]
Da kenne ich mich leider überhaupt nicht aus. Ich habe zwar auch ein HO auf dem RasPi laufen, aber dient mir nur zur Visualisierung von Gasverbrauch und Stromverbrauch.
